### ISSUE TITLE
Filters for level 2+ blessings

### ISSUE THREAD

**Issue by hammerandtongs** [danreeves/dt-exchange#14]
Being able to sort by modifiers is very useful as it allows me to ignore anything below say 350, very useful.

I think that we are going to start to want to horde blessings and so seeing anything over 350 modifier OR rank 2+ blessing seems useful.

Trinkets probably wouldn't be a useful addition to the view at that point since the blessing are all 3.

**Comment by errnoh** [comment]
:+1:, will be part of the shop filtering feature

**Comment by errnoh** [comment]
Fixed by #2
