### ISSUE TITLE
Attributes orders do not match in-game presentation

### ISSUE THREAD

**Issue by azegoca** [danreeves/dt-exchange#20]
The modifiers are not in the same order as in-game, and there are 3 modifiers on the first line, then 2 on the second, where the game is 2 then 3. 

It was mentioned that Curios have the same issue with perks???

It's a small UI thing, but consistency between the UIs would be good.

**Comment by Coconutcoo** [comment]
To clarify the curio issue - in-game curios are presented as Blessings, then Perks. The script right now presents all items as Modifiers, Perks, Blessings.

Nonetheless, both of these are small UI layout issues in Store.tsx, and probably best fixed at the same time.
