### ISSUE TITLE
Investigate removing 'Buffer' library dependency in favor of btoa/atob

### ISSUE THREAD

**Issue by Chris-Bitler** [danreeves/dt-exchange#23]
These functions should serve the same purpose as the buffer library - we currently use the buffer library to match how FatShark base64's the auth data into a storage object, but if btoa and atob also work for the same purpose, this could eliminate ~2000 lines that end up bundled into the background js script

**Comment by danreeves** [comment]
I'm up for finding a smaller alternative but we need to be careful because native btoa doesn't support unicode: https://developer.mozilla.org/en-US/docs/Web/API/btoa#unicode_strings

There are workarounds though

**Comment by danreeves** [comment]
We can do this now FS has also removed their use of it!
