### ISSUE TITLE
Show current mission board details

### ISSUE THREAD

**Issue by Coconutcoo** [danreeves/dt-exchange#28]
GET `https://bsp-td-prod.atoma.cloud/mission-board` with Authorization header, returns something like;

```json
{
    "_links": {
        "self": {
            "href": "/mission-board"
        },
        "mission": {
            "href": "/{missionId}",
            "templated": true
        }
    },
    "missions": [
        {
            "id": "d077822f-40d9-4c8a-a6f8-8ed24aa16618",
            "map": "km_station",
            "flags": {},
            "circumstance": "default",
            "credits": 2280,
            "xp": 1900,
            "extraRewards": {},
            "challenge": 1,
            "resistance": 2,
            "start": "1672840260000",
            "expiry": "1672841219999",
            "requiredLevel": 1,
            "missionGiver": "sergeant_a",
            "displayIndex": 12
        },
        {
            "id": "6b0c91e3-6ec7-41e8-9295-25fa573d32ac",
            "map": "dm_propaganda",
            "flags": {
                "side": {}
            },
            "sideMission": "side_mission_tome",
            "circumstance": "default",
            "credits": 2280,
            "xp": 1900,
            "extraRewards": {
                "sideMission": {
                    "credits": 685,
                    "xp": 360
                }
            },
            "challenge": 1,
            "resistance": 2,
            "start": "1672840440000",
            "expiry": "1672841639999",
            "requiredLevel": 1,
            "missionGiver": "tech_priest_a",
            "displayIndex": 14
        },
        {
            "id": "299cc83b-384a-4fee-ab11-5e8402cd9156",
            "map": "km_station",
            "flags": {},
            "circumstance": "default",
            "credits": 4180,
            "xp": 2000,
            "extraRewards": {},
            "challenge": 2,
            "resistance": 2,
            "start": "1672841160000",
            "expiry": "1672841759999",
            "requiredLevel": 1,
            "missionGiver": "explicator_a",
            "displayIndex": 10
        },
        {
            "id": "762c9db2-5289-4156-a93a-3cc1c886e53f",
            "map": "km_enforcer",
            "flags": {
                "side": {}
            },
            "sideMission": "side_mission_tome",
            "circumstance": "default",
            "credits": 7440,
            "xp": 3100,
            "extraRewards": {
                "sideMission": {
                    "credits": 2230,
                    "xp": 600
                }
            },
            "challenge": 3,
            "resistance": 3,
            "start": "1672840800000",
            "expiry": "1672841819999",
            "requiredLevel": 3,
            "missionGiver": "sergeant_a",
            "displayIndex": 3
        },
        {
            "id": "373c9258-29db-4258-87d7-6d39bfdbc2eb",
            "map": "lm_scavenge",
            "flags": {
                "side": {}
            },
            "sideMission": "side_mission_tome",
            "circumstance": "default",
            "credits": 19950,
            "xp": 5450,
            "extraRewards": {
                "sideMission": {
                    "credits": 5985,
                    "xp": 1070
                }
            },
            "challenge": 5,
            "resistance": 4,
            "start": "1672839180000",
            "expiry": "1672842059999",
            "requiredLevel": 12,
            "missionGiver": "pilot_a",
            "displayIndex": 7
        },
        {
            "id": "4fbe931f-3bce-40df-82f0-ed58eb855393",
            "map": "cm_habs",
            "flags": {
                "side": {}
            },
            "sideMission": "side_mission_tome",
            "circumstance": "default",
            "credits": 7440,
            "xp": 3100,
            "extraRewards": {
                "sideMission": {
                    "credits": 2230,
                    "xp": 600
                }
            },
            "challenge": 3,
            "resistance": 3,
            "start": "1672840920000",
            "expiry": "1672842059999",
            "requiredLevel": 3,
            "missionGiver": "sergeant_a",
            "displayIndex": 6
        },
        {
            "id": "d73d4578-4487-41d7-89ed-bebc531f6d56",
            "map": "fm_cargo",
            "flags": {
                "side": {}
            },
            "sideMission": "side_mission_tome",
            "circumstance": "default",
            "credits": 4180,
            "xp": 2000,
            "extraRewards": {
                "sideMission": {
                    "credits": 1255,
                    "xp": 380
                }
            },
            "challenge": 2,
            "resistance": 2,
            "start": "1672841160000",
            "expiry": "1672842119999",
            "requiredLevel": 1,
            "missionGiver": "sergeant_a",
            "displayIndex": 9
        },
        {
            "id": "f78abeb6-ee49-4ee7-a898-7f7863678ba1",
            "map": "cm_habs",
            "flags": {},
            "circumstance": "default",
            "credits": 4180,
            "xp": 2000,
            "extraRewards": {},
            "challenge": 2,
            "resistance": 2,
            "start": "1672840980000",
            "expiry": "1672842119999",
            "requiredLevel": 1,
            "missionGiver": "sergeant_a",
            "displayIndex": 15
        },
        {
            "id": "1264a8c2-cddd-4c5d-9602-1df919c013ce",
            "map": "hm_strain",
            "flags": {},
            "circumstance": "default",
            "credits": 2280,
            "xp": 1900,
            "extraRewards": {},
            "challenge": 1,
            "resistance": 2,
            "start": "1672841220000",
            "expiry": "1672842359999",
            "requiredLevel": 1,
            "missionGiver": "pilot_a",
            "displayIndex": 13
        },
        {
            "id": "5a395501-2187-47b8-b6e5-bf35effb561f",
            "map": "dm_forge",
            "flags": {},
            "circumstance": "default",
            "credits": 14820,
            "xp": 4250,
            "extraRewards": {},
            "challenge": 4,
            "resistance": 4,
            "start": "1672839960000",
            "expiry": "1672842719999",
            "requiredLevel": 6,
            "missionGiver": "sergeant_a",
            "displayIndex": 11
        },
        {
            "id": "b0ea56b8-661f-410f-b102-ef718c7dff62",
            "map": "fm_resurgence",
            "flags": {
                "side": {}
            },
            "sideMission": "side_mission_grimoire",
            "circumstance": "default",
            "credits": 7440,
            "xp": 3100,
            "extraRewards": {
                "sideMission": {
                    "credits": 2230,
                    "xp": 600
                }
            },
            "challenge": 3,
            "resistance": 3,
            "start": "1672840740000",
            "expiry": "1672842959999",
            "requiredLevel": 3,
            "missionGiver": "sergeant_a",
            "displayIndex": 1
        },
        {
            "id": "04d1d9ba-0538-4c72-927c-c41ed07fb3c6",
            "map": "dm_propaganda",
            "flags": {
                "altered": {},
                "side": {}
            },
            "sideMission": "side_mission_tome",
            "circumstance": "less_resistance_01",
            "credits": 14820,
            "xp": 4250,
            "extraRewards": {
                "circumstance": {
                    "credits": 3705,
                    "xp": 1245
                },
                "sideMission": {
                    "credits": 4445,
                    "xp": 830
                }
            },
            "challenge": 4,
            "resistance": 4,
            "start": "1672840440000",
            "expiry": "1672844339999",
            "requiredLevel": 6,
            "missionGiver": "sergeant_a",
            "displayIndex": 5
        },
        {
            "id": "cae2e76f-33cf-4469-aebf-c8730e30c127",
            "map": "dm_forge",
            "flags": {
                "altered": {}
            },
            "circumstance": "less_resistance_01",
            "credits": 19950,
            "xp": 5450,
            "extraRewards": {
                "circumstance": {
                    "credits": 4990,
                    "xp": 1605
                }
            },
            "challenge": 5,
            "resistance": 4,
            "start": "1672838880000",
            "expiry": "1672845239999",
            "requiredLevel": 12,
            "missionGiver": "tech_priest_a",
            "displayIndex": 4
        }
    ],
    "refreshAt": "1672841219999"
}
```

**Comment by Coconutcoo** [comment]
Some static information about the missions by map_name exist at https://github.com/Cortex-Network/Darkmass-Data-Mining/blob/main/All%20.lua%20Scripts/scripts/settings/mission/templates/transit_mission_templates.lua

We will, however, need to build another set of localisation data for the map names. Can't find that info in any of the datamines either.

**Comment by Coconutcoo** [comment]
missionGiver names can be looked up via https://github.com/Cortex-Network/Darkmass-Data-Mining/blob/main/All%20.lua%20Scripts/scripts/components/dialogue.lua#L122-L218

We still need to find the correct localisation for the following "maps";
- cm_archives
  - Name: 
  - Area: 
- cm_habs
  - Name: `Hab Dreyko`
  - Area: `Transit Hub HL-16-11, "Chasm Terminus"`
  - Objective: `Investigation`
  - Description: `A new form of the Blight has hit Transit Hub HL-16-11 hard. Scan the plague residue and maybe we'll get lucky.`
- dm_forge
  - Name: `Smelter Complex HL-17-36`
  - Area: `Manufactory HL-17-36, "Metalfab 36"`
  - Objective:
  - Description:
- dm_propaganda
  - Name: `Relay Station TRS-150`
  - Area: `Freight Port HL-32-2, "The Hourglass"`
  - Objective: `Disruption`
  - Description: `Heretics have seized a Comms-Plex up in one of the spires and are using it to broadcast propaganda. Shut it down.`
- dm_stockpile
  - Name: `Silo Cluster 18-66/a`
  - Area: `Habzone HL-18-66, "The Torrent"`
  - Objective: `Strike`
  - Description: `The heretics are poisoning Tertium's water. Get into the silo and restore a clean water supply.`
- fm_cargo
  - Name: `Vigil Station Oblivium`
  - Area: `Habzone HL-18-66, "The Torrent"`
  - Objective:
  - Description:
- fm_resurgence
  - Name: `Enclavum Baross`
  - Area: `Habzone HL-19-24 "Throneside"`
  - Objective: `Strike`
  - Description: `You're headed for Enclavum Baross up in Throneside to get its Aegis Station back in our hands.`
- hm_cartel
  - Name: `Vigil Station Oblivium`
  - Area: `Habzone HL-18-66, "The Torrent"`
  - Objective: `Espionage`
  - Description: `Upload some inaccurate recon data to the heretics' cogitator array down in the Torrent.`
- hm_complex
  - Name: `Comms-Plex 154/2f`
  - Area: `Habzone HL-19-24 "Throneside"`
  - Objective: `Espionage`
  - Description: `Use the data-interrogator to access the Archivum Vox Array to send a warzone status report out-system.`
- hm_strain
  - Name: `Refinery Delta-17`
  - Area: `Freight Port HL-32-2, "The Hourglass"`
  - Objective: `Disruption`
  - Description: `The Heretics are brewing a pathogen in one of the Hourglass' fuel refineries. Get access to said refinery and destroy the pathogen.`
- km_enforcer
  - Name: `Magistrati Oubliette TM8-707`
  - Area: `Habzone HL-18-66, "The Torrent"`
  - Objective: `Assassination`
  - Description: `The Kill Target's in the Torrent's Enforcer Station. Navigate the sewers, reach the streets and take them out.`
- km_station
  - Name: `Chasm Station HL-16-11`
  - Area: `Transit Hub HL-16-11, "Chasm Terminus"`
  - Objective: `Assassination`
  - Description: `A warlord is arriving by train. Make your way into Chasm Terminus, and execute the heretic.`
- lm_cooling
  - Name: `Power Matrix HL-17-36`
  - Area: `Manufactory HL-17-36, "Metalfab 36"`
  - Objective: `Repair`
  - Description: `HL-17-36 is heading towards a power systems failure. Access the operations array and use cryonic rods to flush the system.`
- lm_rails
  - Name: `Chasm Logistratum`
  - Area: `Transit Hub HL-16-11, "Chasm Terminus"`
  - Objective: `Raid`
  - Description: `It's time to replenish our special issue ammo reserves. It begins at Chasm Station Logistratum.`
- lm_scavenge
  - Name: `Excise Vault Spireside-13`
  - Area: `Freight Port HL-32-2, "The Hourglass"`
  - Objective: `Raid`
  - Description: `You're off to Sector Periferus to crack an Excise Vault, and get a sample of the heretics' latest contagion.`

There are a lot of circumstances (conditions) defined at https://github.com/Cortex-Network/Darkmass-Data-Mining/tree/main/All%20.lua%20Scripts/scripts/settings/circumstance/templates
For now, I think we need to localise
- more_resistance_01
  - Name: `Hi-Intensity Engagement Zone`
  - Description: `Recon indicates high Enemy concentration in the Mission Zone, along with a higher proportion of Specialists. Expect higher intensity engagements.`
- less_resistance_01
  - Name: `Low-Intensity Engagement Zone`
  - Description: `Recon indicates lower Enemy concentration in the Mission Zone. Expect fewer high intensity engagements and Specialists.`
- hunting_grounds_01
  - Name: `Hunting Grounds`
  - Description: `The enemy have let loose a pack of hounds in the area.`

Finally side missions as defined at https://github.com/Cortex-Network/Darkmass-Data-Mining/blob/main/All%20.lua%20Scripts/scripts/settings/mission_objective/templates/side_mission_objective_template.lua
For now, just
- side_mission_tome
  - Name: `Recover Scriptures`
  - Description: `Recover 3 x Missing Scriptures for additional reward`
- side_mission_grimoire
  - Name: `Seize Grimoires`
  - Description: `Seize Grimoires`

**Comment by danreeves** [comment]
https://www.reddit.com/r/DarkTide/comments/1042aay/live_mission_board_tracker_discord_notifications/

**Comment by Coconutcoo** [comment]
Ah neato - then we shant waste time doing the same here

**Comment by danreeves** [comment]
Might re-open in the future
