### ISSUE TITLE
Tagged Release runs on top of prerelease, breaking since latest already exists

### ISSUE THREAD

**Issue by Coconutcoo** [danreeves/dt-exchange#33]
Right now a commit to main triggers both workflows, and one (possibly deterministically tagged-release?) fails since the other created a new "latest" tag first.

Obviously we'd want to avoid running both, so we could try combine them into one workflow that either does a latest or a tagged release, or maybe some of the logic at https://github.com/danreeves/dt-exchange/blob/main/.github/workflows/tagged-release.yml#L39-L40 is wrong? I'd've imagined this should be `prerelease: false`, and the `automatic-release-tag: github.ref`? (https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)

**Comment by danreeves** [comment]
I messed up copy pasting config around. This should be resolved now 🤞 

Also fixed the PR workflow running on main
