### ISSUE TITLE
pgUp and pgDown while in the editor reformats the page entirely on desktop browser

### ISSUE THREAD

**Issue by Wobin** [danreeves/dt-exchange#41]
![image](https://user-images.githubusercontent.com/2107/210724402-e4df147c-13ac-444e-8d91-3f5ef4b9f936.png)
The initial layout

Pressing pgDown or pgUp results in
![image](https://user-images.githubusercontent.com/2107/210724518-86ca2594-b1b3-4fb9-a8a3-51fa2629d2f6.png)

**Comment by errnoh** [comment]
I'm able to replicate this in Chrome. Doesn't seem to happen in Firefox.

**Comment by errnoh** [comment]
Apparently a known bug in Chrome: https://stackoverflow.com/questions/17808854/pressing-pageup-while-in-textarea-moves-website-out-of-the-window

**Comment by danreeves** [comment]
What a strange bug 😅
