### ISSUE TITLE
Filters provided as an array override requirements inside the whole rule

### ISSUE THREAD

**Issue by Coconutcoo** [danreeves/dt-exchange#44]
A filter like
```json
[
    {
        "Item": "Crucis Mk II Thunder Hammer",
        "blessing": [
            "Momentum",
            "Thrust"
        ],
        "minStats": 340
    }
]
```

Will match items that have anything that would match the blessing "Momentum" or "Thrust", since that array is handled as an "OR" without regard to the other filters. E.g. 
![image](https://user-images.githubusercontent.com/15087570/210926706-deef2c43-60cc-4ea1-9bec-45fa8e76b528.png)

My understanding is the logic above should essentially look for
Item is X && Blessing in [A,B] && minStats > Y

It's acting more like
(Item is X && minStats > Y) || Blessing is A || Blessing is B

**Comment by kuanoni** [comment]
It's because the "Item" in your filter is capitalized. In the filter function it checks item names against `target.item`. Change it to "item" and it works fine.
