### ISSUE TITLE
type: curio + minPerkRarity not correctly filtering

### ISSUE THREAD

**Issue by ExonarAtog** [danreeves/dt-exchange#55]
JSON
`{
        "type": "curio",
        "minPerkRarity": 4
}`

Does not correctly filter to only curios. The same code with "minBlessingRarity" does filter to only curios, not sure why, but yeah.

**Comment by errnoh** [comment]
Investigating this. Found one other issue at least while trying to replicate this, but reporting back here once I have an update

**Comment by errnoh** [comment]
@ExonarAtog so just to be sure, are you running the latest pre-release from the zip? This `type` filter is not yet in the version that's released in firefox/chrome addon stores, but will be on the next released version.

I'm not able to replicate this problem with the current pre-release.

**Comment by ExonarAtog** [comment]
Ah, I am not! That's quite weird actually, because the type appeared to be filtering correctly for minBlessingRarity but maybe something else was going on there. All's good then!
