### ISSUE TITLE
Implement means of filtering for max blessings on curios

### ISSUE THREAD

**Issue by AdamKasdorf** [danreeves/dt-exchange#60]
Blessing values on curios appear to be determined by (or at least indicated by) the rating of the blessing and not the rarity. For example, Ferrocrete Hide and Vitality blessings appear to scale by 1% every 5 rating regardless of rarity, up to max at rating range 75-80 (or possibly 76, I'm not sure where the exact cut-off is).

Possible solution would be to allow for filtering by minBlessingRating.

**Comment by errnoh** [comment]
Turns out that minStats filters curios based on the blessing stats, totally intended 😅 

so if you want to filter for +3 stamina curios for example you would do:
- item type: curio
- min stats: 75
- blessing: Endurance
