### ISSUE TITLE
Include description when matching blessings

### ISSUE THREAD

**Issue by errnoh** [danreeves/dt-exchange#61]
There might be an assumption that when matching blessings it would also match the blessing description. Minor change but probably should be implemented. Makes it simple to match things like +3 stamina curios without having to know the breakpoint for +2 to +3, especially since we don't yet have functionality to filter based on blessing rating.

**Comment by CautemocSg** [comment]
Implemented in this pull request https://github.com/danreeves/dt-exchange/pull/75

**Comment by CautemocSg** [comment]
@errnoh Can we close this? I believe the PR has been merged in now.
