### ISSUE TITLE
Migrate to Mv3

### ISSUE THREAD

**Issue by Coconutcoo** [danreeves/dt-exchange#65]
As of FF109 it's in general availability, but we should confirm that other browsers also have it generally available.

Just need to follow the changes as per https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/ / https://developer.chrome.com/docs/extensions/mv3/mv3-migration/

**Comment by danreeves** [comment]
> Version 109.0, first offered to Release channel users on January 17, 2023

Hot off the press!

**Comment by danreeves** [comment]
This is high priority now because Chrome Web Store is no longer letting me publish it with a v2 manifest
<img width="582" alt="image" src="https://user-images.githubusercontent.com/1973559/229120152-7d89d5e8-4225-4c7a-ac2b-ad4921f53dbd.png">

**Comment by danreeves** [comment]
Done in 1.6ish
