### ISSUE TITLE
Collaborate with Blessings of the Omnissiah mod to indicate if a blessing is already earnt

### ISSUE THREAD

**Issue by Wobin** [danreeves/dt-exchange#68]
Hiho, I'm not sure how easily the extension can access the file system, but I can dump a status of known blessings to a json file in a location like \Warhammer 40,000 DARKTIDE\binaries\dump\blessings.json if you could use that for your filters

**Comment by danreeves** [comment]
It could be possible but I'm not sure how interested I am in further developing new features of the extension TBH

**Comment by Wobin** [comment]
Fair enough, the offer is there for the future

**Comment by danreeves** [comment]
Not to say I wouldn't accept a PR but my time is limited and I think there are better places to focus it 😄

**Comment by danreeves** [comment]
I looked into it a little and I think the experience would be kinda subpar. I believe you'd have to select the file every time you opened the page. Do you know any different?
