### ISSUE TITLE
add mobile support

### ISSUE THREAD

**Issue by mubbelsberger** [danreeves/dt-exchange#84]
The AddOn does not work on FF mobile.
Chrome has no AddOn support on mobile.

On FF Desktop I needed to set "the permission to permanently allow" the addon to on accounts.atoma.cloud.

This option for the AddOn does not exist on FF mobile.

Thank you very much!

**Comment by sdg9** [comment]
FYI I wanted the same thing and here is a workaround I'm doing for Android.

- Download a browser that supports chrome extensions, such as the [Kiwi browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en_US&gl=US)
- Add this [darktide armory extension](https://chromewebstore.google.com/detail/armoury-exchange/hcjihmkcnjkfkaeebhnpjcnnibpoolgc) from the browser
- If desired, make a shortcut to https://accounts.atoma.cloud/dashboard from that browser as a home screen icon

**Comment by mubbelsberger** [comment]
That's working great!

Maybe we can pin this to the reddit thread?
